* reconf: Require autoconf 2.13. Remove support for local autoconf         tree.
git-svn-id: svn://anonsvn.mit.edu/krb5/trunk@13847 dc483132-0cff-0310-8789-dd5450dbe970

diff --git a/src/util/reconf b/src/util/reconf
--- a/src/util/reconf
+++ b/src/util/reconf
@@ -1,9 +1,9 @@
 #!/bin/sh
 
 force=
-autoreconfprog=./util/autoconf/autoreconf
+autoreconfprog=autoreconf
 localdir=.
-autoreconfoptions="-m util/autoconf"
+autoreconfoptions=""
 verbose=false
 
 autoreconf="/bin/sh $autoreconfprog"
@@ -23,39 +23,35 @@ do
   esac
 done
 
-# Currently (2000-10-03) we need 2.12 or later, and 2.13 is current.
-# Thie pattern also recognizes 2.40 and up.
-patb="2.(1[2-9])|([4-9][0-9])"
+# Currently (2000-10-03) we need 2.13 or later.
+# The pattern also recognizes 2.40 and up.
+patb="2.(1[3-9])|([4-9][0-9])"
 
 # sedcmd1 recognizes the older 2.12 version, and sedcmd2 the newer 2.49
 sedcmd1="s,.*version \(.*\)$,\1,"
 sedcmd2="s,.*) \(.*\)$,\1,;1q"
 
-if test ! -f $autoreconfprog ; then
-	if autoreconf --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null && \
-	   autoconf --version  | sed -e "$sedcmd1" -e "$sedcmd2"  | egrep "$patb" >/dev/null && \
-	   autoheader --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null; then
-		autoreconf=autoreconf
-		autoreconfoptions=
-		autoconfversion=`autoconf --version | sed -e "$sedcmd1" -e "$sedcmd2"`
-		echo "Using autoconf version $autoconfversion found in your path..."
-		# Determine if localdir needs to be relative or absolute
-		case "$autoconfversion" in
-		  2.1*)
-		       localdir=.
-		       ;;
-		     *)
-		       localdir=`pwd`
-		       ;;
-		esac
-	else
-		echo "Couldn't find autoconf 2.12 or higher in your path."
-		echo " "
-		echo "Please cd to util/autoconf, and type the commands"
-		echo "'configure' and then 'make'; then cd back to the top"
-		echo "of the source tree and re-run ./util/reconf"
-		exit 1
-	fi
+if autoreconf --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null && \
+    autoconf --version  | sed -e "$sedcmd1" -e "$sedcmd2"  | egrep "$patb" >/dev/null && \
+    autoheader --version | sed -e "$sedcmd1" -e "$sedcmd2" | egrep "$patb" >/dev/null; then
+    autoreconf=autoreconf
+    autoreconfoptions=
+    autoconfversion=`autoconf --version | sed -e "$sedcmd1" -e "$sedcmd2"`
+	echo "Using autoconf version $autoconfversion found in your path..."
+	# Determine if localdir needs to be relative or absolute
+	case "$autoconfversion" in
+	  2.1*)
+	       localdir=.
+	       ;;
+	     *)
+	       localdir=`pwd`
+	       ;;
+	esac
+else
+	echo "Couldn't find autoconf 2.13 or higher in your path."
+	echo " "
+	echo "Please install or add to your path and re-run ./util/reconf"
+	exit 1
 fi
 
 if $verbose ; then 
