* post.in,pre.in: break some things out from aclocal.m4 and put 		them here
git-svn-id: svn://anonsvn.mit.edu/krb5/trunk@8361 dc483132-0cff-0310-8789-dd5450dbe970

diff --git a/src/config/post.in b/src/config/post.in
--- a/src/config/post.in
+++ b/src/config/post.in
@@ -35,3 +35,36 @@ clean-unix::
 clean-windows::
 	$(RM) *.$(OBJEXT)
 	$(RM) msvc.pdb *.err
+
+Makefiles:: Makefile
+
+Makefile: $(srcdir)/Makefile.in $(thisconfigdir)/config.status \
+		$(SRCTOP)/config/pre.in $(SRCTOP)/config/post.in
+	cd $(thisconfigdir) && $(SHELL) config.status
+$(thisconfigdir)/config.status: $(srcdir)/$(thisconfigdir)/configure
+	cd $(thisconfigdir) && $(SHELL) config.status --recheck
+$(srcdir)/$(thisconfigdir)/configure: $(srcdir)/$(thisconfigdir)/configure.in \
+		$(SRCTOP)/aclocal.m4
+	cd $(srcdir)/$(thisconfigdir) && \
+		$(SHELL) $(SRCTOP)/util/autoconf/autoconf \
+			--localdir=$(BUILDTOP) \
+			--macrodir=$(BUILDTOP)/util/autoconf
+
+#These don't work well with some versions of GNU make.
+#all-unix clean-unix install-unix check-unix Makefiles::
+#	@case "`echo '$(MAKEFLAGS)'|sed -e 's/ --.*$$//'`" in \
+#		*[ik]*) e=:;; *) e="exit 1";; esac;
+
+@RECURSE_TARGETS@::
+	@e="exit 1"; \
+	for i in $(SUBDIRS) ; do \
+		if test -d $$i ; then \
+			target=`echo $@|sed s/-unix//`; \
+			echo "making $$target in $(CURRENT_DIR)$$i..."; \
+			if (cd $$i ; $(MAKE) CC="$(CC)" CCOPTS="$(CCOPTS)" \
+			    CURRENT_DIR=$(CURRENT_DIR)$$i/ $$target) then :; \
+			else $$e; fi; \
+		else \
+			echo "Skipping missing directory $(CURRENT_DIR)$$i" ; \
+		fi \
+	done
