* Makefile.in (check-unix): Test to see if krb5-config outputs 	variables that require Makefile substitutions.
	* krb5-config.in: Remore $(PURE) from output. Handle variables
	$(RPATH_FLAG) and $(LDFLAGS).

If config/shlib.conf is changed again, we will detect brokeness in
krb5-config before the release.

ticket: 1311

git-svn-id: svn://anonsvn.mit.edu/krb5/trunk@15120 dc483132-0cff-0310-8789-dd5450dbe970

diff --git a/src/Makefile.in b/src/Makefile.in
--- a/src/Makefile.in
+++ b/src/Makefile.in
@@ -568,3 +568,16 @@ install-unix::
 krb5-config: $(srcdir)/krb5-config.in $(thisconfigdir)/config.status
 	cd $(thisconfigdir) && $(SHELL) config.status krb5-config
 
+# Test to ensure that krb5-config does not spit out things like
+# $(PURE) or $(LDFLAGS) in case someone changes config/shlib.conf
+check-unix:: krb5-config
+	@echo "Testing if krb5-config outputs shell variables"
+	@if `./krb5-config --libs kdb | egrep -s '\\$$'`; then \
+	   echo "Error './krb5-config --libs kdb' contains shell variables"; \
+	   exit 1; \
+	 fi
+	@if `./krb5-config --cflags | egrep -s '\\$$'`; then \
+	   echo "Error './krb5-config --cflags' contains shell variables"; \
+	   exit 1; \
+	 fi
+	@echo "krb5-config appears ok"
