Fix some syntax issues in testing krb5-config output
git-svn-id: svn://anonsvn.mit.edu/krb5/trunk@19269 dc483132-0cff-0310-8789-dd5450dbe970

diff --git a/src/t_krbconf b/src/t_krbconf
--- a/src/t_krbconf
+++ b/src/t_krbconf
@@ -24,15 +24,15 @@
 
 echo "Testing if krb5-config outputs shell variables"
 echo "  Testing --libs argument"
-if `./krb5-config --libs kdb | egrep -s '\\$'`; then 
-	echo "Error './krb5-config --libs kdb' contains shell variables"; 
-	exit 1; 
+if ./krb5-config --libs kdb | egrep -s '\$' > /dev/null; then
+	echo "Error './krb5-config --libs kdb' contains shell variables"
+	exit 1
 fi
 
 echo "  Testing --cflags argument"
-if `./krb5-config --cflags | egrep -s '\\$'`; then \
-	echo "Error './krb5-config --cflags' contains shell variables"; \
-	exit 1; \
+if ./krb5-config --cflags | egrep -s '\$' > /dev/null; then
+	echo "Error './krb5-config --cflags' contains shell variables"
+	exit 1
 fi
 echo "krb5-config tests pass"
 exit 0
